# Generated by Django 3.2.9 on 2021-11-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_administrator',
        ),
    ]
