# Generated by Django 3.2.9 on 2021-11-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dog_breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dog_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dog_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
