# Generated by Django 3.2.9 on 2021-11-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
