# Generated by Django 3.2.9 on 2021-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211114_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
