# Generated by Django 3.2.9 on 2021-11-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211114_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Activity',
        ),
    ]
